repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: end-of-file-fixer

  - repo: local
    hooks:
    - id: isort
      name: isort
      stages: [commit]
      language: system
      entry: isort
      types: [python]

    - id: black
      name: black
      stages: [commit]
      language: system
      entry: black
      types: [python]
