repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: end-of-file-fixer

    - id: black
      name: black
      stages: [commit]
      language: system
      entry: black
      types: [python]
