dist: bionic
language: python
python:
    - "3.7"
    - "nightly"

before_install:
    - sudo apt-get install texlive
    # Ubuntu's latexmk is still bugged. Need to get latest version for tests
    - wget http://mirrors.ctan.org/support/latexmk.zip
    - unzip latexmk.zip
    - mv latexmk/latexmk.pl /usr/bin/latexmk


install:
    - pip install poetry
    - poetry install

script:
    - make tests
    - make lint

after_success:
  - coveralls --verbose
