dist: xenial
language: python
python:
    - "3.7"
    - "nightly"

before_install:
    - sudo apt-get install texlive

install:
    - pip install poetry
    - poetry install

script:
    - make tests
    - make lint

after_success:
  - coveralls --verbose
