dist: bionic
language: python
python:
    - "3.6"
    - "3.7"
    - "nightly"

install:
    - pip install poetry
    - pip install crossref-commons
    - poetry install

script:
    - make tests
    - make lint

after_success:
  - coveralls
