dist: xenial
language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "nightly"

install:
    - pip install poetry
    - pip install python-coveralls

script:
    - make tests
    - make lint

after_success:
  - coveralls --verbose
