
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='caleb',
    version='0.7.0',
    description='A tool to automatically retrieve bibtex entries',
    python_requires='==3.*,>=3.6.0',
    project_urls={'homepage': 'https://github.com/kevinywlui/caleb'},
    author='kevin lui',
    author_email='kevinywlui@gmail.com',
    license='MIT',
    keywords='latex python crossref',
    classifiers=['Topic :: Text Processing :: Markup :: LaTeX', 'Programming Language :: Python :: 3', 'License :: OSI Approved :: MIT License', 'Operating System :: OS Independent'],
    entry_points={'console_scripts': ['caleb = caleb.cmdline:launch']},
    packages=['caleb'],
    package_data={},
    install_requires=['crossref-commons==0.*,>=0.0.6', 'mypy==0.*,>=0.720.0', 'requests==2.*,>=2.22.0'],
    extras_require={'dev': ['black==18.*,>=18.3.0', 'poetry-setup==0.*,>=0.3.6', 'pytest==5.*,>=5.0.0', 'pytest-cov==2.*,>=2.7.0', 'python-coveralls==2.*,>=2.9.0']},
)
